# Generated by Django 2.0.1 on 2018-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20180114_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='请填写完整、规范的通讯地址。如在国外，可使用外文地址。', max_length=250, verbose_name='通讯地址'),
        ),
    ]
