# Generated by Django 2.0.1 on 2018-01-15 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='email_prefix',
            field=models.CharField(blank=True, help_text='如果要开通 @tsinghua.org.cn 校友邮箱，请填写想要的用户名前缀。用户名前缀的合法字符包括英文字母、减号和下划线。英文字母不区分大小写，用户名将自动加入 04 作为后缀。', max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z_-]*[A-Za-z]$', '邮箱用户名前缀不合法。')], verbose_name='校友邮箱用户名前缀'),
        ),
    ]
