# Generated by Django 2.0.1 on 2018-01-15 13:48

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_extra_email_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='photo',
            field=models.ImageField(blank=True, help_text='如要要办理校友卡，请上传证件照。', upload_to=contacts.models.get_photo_upload_path, verbose_name='校友卡证件照'),
        ),
    ]
