# Generated by Django 2.0.1 on 2018-01-26 15:21

import contacts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20180122_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='如要要办理校友卡，请上传证件照。', upload_to=contacts.models.get_photo_upload_path, verbose_name='校友卡证件照'),
        ),
    ]
