# Generated by Django 2.0.1 on 2018-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20180126_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remark',
            field=models.CharField(blank=True, help_text='如果以上内容有特殊情况的，可在备注栏中说明。例如：学籍信息有误；有多个手机号、邮箱；有多个常住地等。', max_length=250, verbose_name='备注'),
        ),
    ]
