# Generated by Django 2.0.1 on 2018-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20180131_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
