# Generated by Django 2.0.2 on 2018-02-11 12:06

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20180211_1722_squashed_0016_auto_20180211_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clazzes',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='contacts.Clazz', verbose_name='班级'),
        ),
    ]
