# Generated by Django 2.0.2 on 2018-02-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_upgrade_clazz_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clazz',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='department',
        ),
    ]
