# Generated by Django 2.0.2 on 2018-02-12 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('contacts', '0019_auto_20180212_1548'), ('contacts', '0020_auto_20180212_1639')]

    dependencies = [
        ('contacts', '0018_auto_20180211_2040'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clazz',
            name='linkmen',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='召集人'),
        ),
        migrations.AddField(
            model_name='department',
            name='linkmen',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='召集人'),
        ),
    ]
