# Generated by Django 2.0.2 on 2018-02-12 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0018_auto_20180211_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='clazz',
            name='linkmen',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='召集人'),
        ),
        migrations.AddField(
            model_name='department',
            name='linkmen',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='召集人'),
        ),
    ]
