# Generated by Django 2.0.2 on 2018-02-19 15:16

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_unique_name_and_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clazzes',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='contacts.Clazz', verbose_name='班级'),
        ),
    ]
