# Generated by Django 2.0.2 on 2018-02-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_replace_clazz_with_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
