# Generated by Django 2.0.2 on 2018-04-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_add_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='photo_valid',
            field=models.BooleanField(default=False, verbose_name='校友卡证件照是否合格'),
            preserve_default=False,
        ),
    ]
