# Generated by Django 2.0.1 on 2018-01-11 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('enroll_year', models.IntegerField()),
                ('graduate_year', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('clazz', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('wechat', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
