# Generated by Django 2.0.1 on 2018-01-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['idnum'], 'verbose_name': '个人信息', 'verbose_name_plural': '个人信息'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='通讯地址'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='clazz',
            field=models.CharField(max_length=100, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=100, verbose_name='院系'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='enroll_year',
            field=models.IntegerField(verbose_name='入学年份'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduate_year',
            field=models.IntegerField(verbose_name='毕业年份'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idnum',
            field=models.CharField(max_length=10, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在行业'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='所在地区'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.CharField(max_length=100, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, verbose_name='工作单位'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='邮编'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, verbose_name='固定电话'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='职称'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wechat',
            field=models.CharField(blank=True, max_length=100, verbose_name='微信号'),
        ),
    ]
