# Generated by Django 2.0.1 on 2018-01-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180111_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name'], 'verbose_name': '个人信息', 'verbose_name_plural': '个人信息'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='idnum',
        ),
    ]
