# Generated by Django 2.0.1 on 2018-01-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180112_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['student_id'], 'verbose_name': '个人信息', 'verbose_name_plural': '个人信息'},
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='电子邮箱'),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(default='2004010000', max_length=10, verbose_name='学号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='enroll_year',
            field=models.IntegerField(default=2004, verbose_name='入学年份'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='graduate_year',
            field=models.IntegerField(default=2008, verbose_name='毕业年份'),
        ),
    ]
